//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OutDoor_Guide.WebServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WebServiceReference.SyncSoap")]
    public interface SyncSoap {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/carre", ReplyAction="*")]
        System.IAsyncResult Begincarre(int a, System.AsyncCallback callback, object asyncState);
        
        int Endcarre(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/hello", ReplyAction="*")]
        System.IAsyncResult Beginhello(OutDoor_Guide.WebServiceReference.helloRequest request, System.AsyncCallback callback, object asyncState);
        
        OutDoor_Guide.WebServiceReference.helloResponse Endhello(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/VerifyWb", ReplyAction="*")]
        System.IAsyncResult BeginVerifyWb(OutDoor_Guide.WebServiceReference.VerifyWbRequest request, System.AsyncCallback callback, object asyncState);
        
        OutDoor_Guide.WebServiceReference.VerifyWbResponse EndVerifyWb(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/getServerDate", ReplyAction="*")]
        System.IAsyncResult BegingetServerDate(OutDoor_Guide.WebServiceReference.getServerDateRequest request, System.AsyncCallback callback, object asyncState);
        
        OutDoor_Guide.WebServiceReference.getServerDateResponse EndgetServerDate(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/getDataBaseDefinitions", ReplyAction="*")]
        System.IAsyncResult BegingetDataBaseDefinitions(OutDoor_Guide.WebServiceReference.getDataBaseDefinitionsRequest request, System.AsyncCallback callback, object asyncState);
        
        OutDoor_Guide.WebServiceReference.getDataBaseDefinitionsResponse EndgetDataBaseDefinitions(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/setUpdate", ReplyAction="*")]
        System.IAsyncResult BeginsetUpdate(OutDoor_Guide.WebServiceReference.setUpdateRequest request, System.AsyncCallback callback, object asyncState);
        
        OutDoor_Guide.WebServiceReference.setUpdateResponse EndsetUpdate(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/getTableData", ReplyAction="*")]
        System.IAsyncResult BegingetTableData(OutDoor_Guide.WebServiceReference.getTableDataRequest request, System.AsyncCallback callback, object asyncState);
        
        OutDoor_Guide.WebServiceReference.getTableDataResponse EndgetTableData(System.IAsyncResult result);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute()]
    public partial class helloRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="hello", Namespace="http://tempuri.org/", Order=0)]
        public OutDoor_Guide.WebServiceReference.helloRequestBody Body;
        
        public helloRequest() {
        }
        
        public helloRequest(OutDoor_Guide.WebServiceReference.helloRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class helloRequestBody {
        
        public helloRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute()]
    public partial class helloResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="helloResponse", Namespace="http://tempuri.org/", Order=0)]
        public OutDoor_Guide.WebServiceReference.helloResponseBody Body;
        
        public helloResponse() {
        }
        
        public helloResponse(OutDoor_Guide.WebServiceReference.helloResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class helloResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string helloResult;
        
        public helloResponseBody() {
        }
        
        public helloResponseBody(string helloResult) {
            this.helloResult = helloResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute()]
    public partial class VerifyWbRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="VerifyWb", Namespace="http://tempuri.org/", Order=0)]
        public OutDoor_Guide.WebServiceReference.VerifyWbRequestBody Body;
        
        public VerifyWbRequest() {
        }
        
        public VerifyWbRequest(OutDoor_Guide.WebServiceReference.VerifyWbRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class VerifyWbRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string RessourceID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string deviceID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string IP;
        
        public VerifyWbRequestBody() {
        }
        
        public VerifyWbRequestBody(string RessourceID, string deviceID, string IP) {
            this.RessourceID = RessourceID;
            this.deviceID = deviceID;
            this.IP = IP;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute()]
    public partial class VerifyWbResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="VerifyWbResponse", Namespace="http://tempuri.org/", Order=0)]
        public OutDoor_Guide.WebServiceReference.VerifyWbResponseBody Body;
        
        public VerifyWbResponse() {
        }
        
        public VerifyWbResponse(OutDoor_Guide.WebServiceReference.VerifyWbResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class VerifyWbResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string VerifyWbResult;
        
        public VerifyWbResponseBody() {
        }
        
        public VerifyWbResponseBody(string VerifyWbResult) {
            this.VerifyWbResult = VerifyWbResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute()]
    public partial class getServerDateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getServerDate", Namespace="http://tempuri.org/", Order=0)]
        public OutDoor_Guide.WebServiceReference.getServerDateRequestBody Body;
        
        public getServerDateRequest() {
        }
        
        public getServerDateRequest(OutDoor_Guide.WebServiceReference.getServerDateRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class getServerDateRequestBody {
        
        public getServerDateRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute()]
    public partial class getServerDateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getServerDateResponse", Namespace="http://tempuri.org/", Order=0)]
        public OutDoor_Guide.WebServiceReference.getServerDateResponseBody Body;
        
        public getServerDateResponse() {
        }
        
        public getServerDateResponse(OutDoor_Guide.WebServiceReference.getServerDateResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getServerDateResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getServerDateResult;
        
        public getServerDateResponseBody() {
        }
        
        public getServerDateResponseBody(string getServerDateResult) {
            this.getServerDateResult = getServerDateResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute()]
    public partial class getDataBaseDefinitionsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getDataBaseDefinitions", Namespace="http://tempuri.org/", Order=0)]
        public OutDoor_Guide.WebServiceReference.getDataBaseDefinitionsRequestBody Body;
        
        public getDataBaseDefinitionsRequest() {
        }
        
        public getDataBaseDefinitionsRequest(OutDoor_Guide.WebServiceReference.getDataBaseDefinitionsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getDataBaseDefinitionsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string appName;
        
        public getDataBaseDefinitionsRequestBody() {
        }
        
        public getDataBaseDefinitionsRequestBody(string appName) {
            this.appName = appName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute()]
    public partial class getDataBaseDefinitionsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getDataBaseDefinitionsResponse", Namespace="http://tempuri.org/", Order=0)]
        public OutDoor_Guide.WebServiceReference.getDataBaseDefinitionsResponseBody Body;
        
        public getDataBaseDefinitionsResponse() {
        }
        
        public getDataBaseDefinitionsResponse(OutDoor_Guide.WebServiceReference.getDataBaseDefinitionsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getDataBaseDefinitionsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getDataBaseDefinitionsResult;
        
        public getDataBaseDefinitionsResponseBody() {
        }
        
        public getDataBaseDefinitionsResponseBody(string getDataBaseDefinitionsResult) {
            this.getDataBaseDefinitionsResult = getDataBaseDefinitionsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute()]
    public partial class setUpdateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="setUpdate", Namespace="http://tempuri.org/", Order=0)]
        public OutDoor_Guide.WebServiceReference.setUpdateRequestBody Body;
        
        public setUpdateRequest() {
        }
        
        public setUpdateRequest(OutDoor_Guide.WebServiceReference.setUpdateRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class setUpdateRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string appName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string param;
        
        public setUpdateRequestBody() {
        }
        
        public setUpdateRequestBody(string appName, string name, string param) {
            this.appName = appName;
            this.name = name;
            this.param = param;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute()]
    public partial class setUpdateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="setUpdateResponse", Namespace="http://tempuri.org/", Order=0)]
        public OutDoor_Guide.WebServiceReference.setUpdateResponseBody Body;
        
        public setUpdateResponse() {
        }
        
        public setUpdateResponse(OutDoor_Guide.WebServiceReference.setUpdateResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class setUpdateResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string setUpdateResult;
        
        public setUpdateResponseBody() {
        }
        
        public setUpdateResponseBody(string setUpdateResult) {
            this.setUpdateResult = setUpdateResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute()]
    public partial class getTableDataRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getTableData", Namespace="http://tempuri.org/", Order=0)]
        public OutDoor_Guide.WebServiceReference.getTableDataRequestBody Body;
        
        public getTableDataRequest() {
        }
        
        public getTableDataRequest(OutDoor_Guide.WebServiceReference.getTableDataRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getTableDataRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string appName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string param;
        
        public getTableDataRequestBody() {
        }
        
        public getTableDataRequestBody(string appName, string name, string param) {
            this.appName = appName;
            this.name = name;
            this.param = param;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute()]
    public partial class getTableDataResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getTableDataResponse", Namespace="http://tempuri.org/", Order=0)]
        public OutDoor_Guide.WebServiceReference.getTableDataResponseBody Body;
        
        public getTableDataResponse() {
        }
        
        public getTableDataResponse(OutDoor_Guide.WebServiceReference.getTableDataResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getTableDataResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getTableDataResult;
        
        public getTableDataResponseBody() {
        }
        
        public getTableDataResponseBody(string getTableDataResult) {
            this.getTableDataResult = getTableDataResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SyncSoapChannel : OutDoor_Guide.WebServiceReference.SyncSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class carreCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public carreCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public int Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class helloCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public helloCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class VerifyWbCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public VerifyWbCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class getServerDateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public getServerDateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class getDataBaseDefinitionsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public getDataBaseDefinitionsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class setUpdateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public setUpdateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class getTableDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public getTableDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SyncSoapClient : System.ServiceModel.ClientBase<OutDoor_Guide.WebServiceReference.SyncSoap>, OutDoor_Guide.WebServiceReference.SyncSoap {
        
        private BeginOperationDelegate onBegincarreDelegate;
        
        private EndOperationDelegate onEndcarreDelegate;
        
        private System.Threading.SendOrPostCallback oncarreCompletedDelegate;
        
        private BeginOperationDelegate onBeginhelloDelegate;
        
        private EndOperationDelegate onEndhelloDelegate;
        
        private System.Threading.SendOrPostCallback onhelloCompletedDelegate;
        
        private BeginOperationDelegate onBeginVerifyWbDelegate;
        
        private EndOperationDelegate onEndVerifyWbDelegate;
        
        private System.Threading.SendOrPostCallback onVerifyWbCompletedDelegate;
        
        private BeginOperationDelegate onBegingetServerDateDelegate;
        
        private EndOperationDelegate onEndgetServerDateDelegate;
        
        private System.Threading.SendOrPostCallback ongetServerDateCompletedDelegate;
        
        private BeginOperationDelegate onBegingetDataBaseDefinitionsDelegate;
        
        private EndOperationDelegate onEndgetDataBaseDefinitionsDelegate;
        
        private System.Threading.SendOrPostCallback ongetDataBaseDefinitionsCompletedDelegate;
        
        private BeginOperationDelegate onBeginsetUpdateDelegate;
        
        private EndOperationDelegate onEndsetUpdateDelegate;
        
        private System.Threading.SendOrPostCallback onsetUpdateCompletedDelegate;
        
        private BeginOperationDelegate onBegingetTableDataDelegate;
        
        private EndOperationDelegate onEndgetTableDataDelegate;
        
        private System.Threading.SendOrPostCallback ongetTableDataCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public SyncSoapClient() : 
                base(SyncSoapClient.GetDefaultBinding(), SyncSoapClient.GetDefaultEndpointAddress()) {
        }
        
        public SyncSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(SyncSoapClient.GetBindingForEndpoint(endpointConfiguration), SyncSoapClient.GetEndpointAddress(endpointConfiguration)) {
        }
        
        public SyncSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(SyncSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress)) {
        }
        
        public SyncSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(SyncSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress) {
        }
        
        public SyncSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<carreCompletedEventArgs> carreCompleted;
        
        public event System.EventHandler<helloCompletedEventArgs> helloCompleted;
        
        public event System.EventHandler<VerifyWbCompletedEventArgs> VerifyWbCompleted;
        
        public event System.EventHandler<getServerDateCompletedEventArgs> getServerDateCompleted;
        
        public event System.EventHandler<getDataBaseDefinitionsCompletedEventArgs> getDataBaseDefinitionsCompleted;
        
        public event System.EventHandler<setUpdateCompletedEventArgs> setUpdateCompleted;
        
        public event System.EventHandler<getTableDataCompletedEventArgs> getTableDataCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult OutDoor_Guide.WebServiceReference.SyncSoap.Begincarre(int a, System.AsyncCallback callback, object asyncState) {
            return base.Channel.Begincarre(a, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        int OutDoor_Guide.WebServiceReference.SyncSoap.Endcarre(System.IAsyncResult result) {
            return base.Channel.Endcarre(result);
        }
        
        private System.IAsyncResult OnBegincarre(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int a = ((int)(inValues[0]));
            return ((OutDoor_Guide.WebServiceReference.SyncSoap)(this)).Begincarre(a, callback, asyncState);
        }
        
        private object[] OnEndcarre(System.IAsyncResult result) {
            int retVal = ((OutDoor_Guide.WebServiceReference.SyncSoap)(this)).Endcarre(result);
            return new object[] {
                    retVal};
        }
        
        private void OncarreCompleted(object state) {
            if ((this.carreCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.carreCompleted(this, new carreCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void carreAsync(int a) {
            this.carreAsync(a, null);
        }
        
        public void carreAsync(int a, object userState) {
            if ((this.onBegincarreDelegate == null)) {
                this.onBegincarreDelegate = new BeginOperationDelegate(this.OnBegincarre);
            }
            if ((this.onEndcarreDelegate == null)) {
                this.onEndcarreDelegate = new EndOperationDelegate(this.OnEndcarre);
            }
            if ((this.oncarreCompletedDelegate == null)) {
                this.oncarreCompletedDelegate = new System.Threading.SendOrPostCallback(this.OncarreCompleted);
            }
            base.InvokeAsync(this.onBegincarreDelegate, new object[] {
                        a}, this.onEndcarreDelegate, this.oncarreCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult OutDoor_Guide.WebServiceReference.SyncSoap.Beginhello(OutDoor_Guide.WebServiceReference.helloRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.Beginhello(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult Beginhello(System.AsyncCallback callback, object asyncState) {
            OutDoor_Guide.WebServiceReference.helloRequest inValue = new OutDoor_Guide.WebServiceReference.helloRequest();
            inValue.Body = new OutDoor_Guide.WebServiceReference.helloRequestBody();
            return ((OutDoor_Guide.WebServiceReference.SyncSoap)(this)).Beginhello(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        OutDoor_Guide.WebServiceReference.helloResponse OutDoor_Guide.WebServiceReference.SyncSoap.Endhello(System.IAsyncResult result) {
            return base.Channel.Endhello(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private string Endhello(System.IAsyncResult result) {
            OutDoor_Guide.WebServiceReference.helloResponse retVal = ((OutDoor_Guide.WebServiceReference.SyncSoap)(this)).Endhello(result);
            return retVal.Body.helloResult;
        }
        
        private System.IAsyncResult OnBeginhello(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return this.Beginhello(callback, asyncState);
        }
        
        private object[] OnEndhello(System.IAsyncResult result) {
            string retVal = this.Endhello(result);
            return new object[] {
                    retVal};
        }
        
        private void OnhelloCompleted(object state) {
            if ((this.helloCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.helloCompleted(this, new helloCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void helloAsync() {
            this.helloAsync(null);
        }
        
        public void helloAsync(object userState) {
            if ((this.onBeginhelloDelegate == null)) {
                this.onBeginhelloDelegate = new BeginOperationDelegate(this.OnBeginhello);
            }
            if ((this.onEndhelloDelegate == null)) {
                this.onEndhelloDelegate = new EndOperationDelegate(this.OnEndhello);
            }
            if ((this.onhelloCompletedDelegate == null)) {
                this.onhelloCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnhelloCompleted);
            }
            base.InvokeAsync(this.onBeginhelloDelegate, null, this.onEndhelloDelegate, this.onhelloCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult OutDoor_Guide.WebServiceReference.SyncSoap.BeginVerifyWb(OutDoor_Guide.WebServiceReference.VerifyWbRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginVerifyWb(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult BeginVerifyWb(string RessourceID, string deviceID, string IP, System.AsyncCallback callback, object asyncState) {
            OutDoor_Guide.WebServiceReference.VerifyWbRequest inValue = new OutDoor_Guide.WebServiceReference.VerifyWbRequest();
            inValue.Body = new OutDoor_Guide.WebServiceReference.VerifyWbRequestBody();
            inValue.Body.RessourceID = RessourceID;
            inValue.Body.deviceID = deviceID;
            inValue.Body.IP = IP;
            return ((OutDoor_Guide.WebServiceReference.SyncSoap)(this)).BeginVerifyWb(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        OutDoor_Guide.WebServiceReference.VerifyWbResponse OutDoor_Guide.WebServiceReference.SyncSoap.EndVerifyWb(System.IAsyncResult result) {
            return base.Channel.EndVerifyWb(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private string EndVerifyWb(System.IAsyncResult result) {
            OutDoor_Guide.WebServiceReference.VerifyWbResponse retVal = ((OutDoor_Guide.WebServiceReference.SyncSoap)(this)).EndVerifyWb(result);
            return retVal.Body.VerifyWbResult;
        }
        
        private System.IAsyncResult OnBeginVerifyWb(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string RessourceID = ((string)(inValues[0]));
            string deviceID = ((string)(inValues[1]));
            string IP = ((string)(inValues[2]));
            return this.BeginVerifyWb(RessourceID, deviceID, IP, callback, asyncState);
        }
        
        private object[] OnEndVerifyWb(System.IAsyncResult result) {
            string retVal = this.EndVerifyWb(result);
            return new object[] {
                    retVal};
        }
        
        private void OnVerifyWbCompleted(object state) {
            if ((this.VerifyWbCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.VerifyWbCompleted(this, new VerifyWbCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void VerifyWbAsync(string RessourceID, string deviceID, string IP) {
            this.VerifyWbAsync(RessourceID, deviceID, IP, null);
        }
        
        public void VerifyWbAsync(string RessourceID, string deviceID, string IP, object userState) {
            if ((this.onBeginVerifyWbDelegate == null)) {
                this.onBeginVerifyWbDelegate = new BeginOperationDelegate(this.OnBeginVerifyWb);
            }
            if ((this.onEndVerifyWbDelegate == null)) {
                this.onEndVerifyWbDelegate = new EndOperationDelegate(this.OnEndVerifyWb);
            }
            if ((this.onVerifyWbCompletedDelegate == null)) {
                this.onVerifyWbCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnVerifyWbCompleted);
            }
            base.InvokeAsync(this.onBeginVerifyWbDelegate, new object[] {
                        RessourceID,
                        deviceID,
                        IP}, this.onEndVerifyWbDelegate, this.onVerifyWbCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult OutDoor_Guide.WebServiceReference.SyncSoap.BegingetServerDate(OutDoor_Guide.WebServiceReference.getServerDateRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BegingetServerDate(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult BegingetServerDate(System.AsyncCallback callback, object asyncState) {
            OutDoor_Guide.WebServiceReference.getServerDateRequest inValue = new OutDoor_Guide.WebServiceReference.getServerDateRequest();
            inValue.Body = new OutDoor_Guide.WebServiceReference.getServerDateRequestBody();
            return ((OutDoor_Guide.WebServiceReference.SyncSoap)(this)).BegingetServerDate(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        OutDoor_Guide.WebServiceReference.getServerDateResponse OutDoor_Guide.WebServiceReference.SyncSoap.EndgetServerDate(System.IAsyncResult result) {
            return base.Channel.EndgetServerDate(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private string EndgetServerDate(System.IAsyncResult result) {
            OutDoor_Guide.WebServiceReference.getServerDateResponse retVal = ((OutDoor_Guide.WebServiceReference.SyncSoap)(this)).EndgetServerDate(result);
            return retVal.Body.getServerDateResult;
        }
        
        private System.IAsyncResult OnBegingetServerDate(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return this.BegingetServerDate(callback, asyncState);
        }
        
        private object[] OnEndgetServerDate(System.IAsyncResult result) {
            string retVal = this.EndgetServerDate(result);
            return new object[] {
                    retVal};
        }
        
        private void OngetServerDateCompleted(object state) {
            if ((this.getServerDateCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.getServerDateCompleted(this, new getServerDateCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void getServerDateAsync() {
            this.getServerDateAsync(null);
        }
        
        public void getServerDateAsync(object userState) {
            if ((this.onBegingetServerDateDelegate == null)) {
                this.onBegingetServerDateDelegate = new BeginOperationDelegate(this.OnBegingetServerDate);
            }
            if ((this.onEndgetServerDateDelegate == null)) {
                this.onEndgetServerDateDelegate = new EndOperationDelegate(this.OnEndgetServerDate);
            }
            if ((this.ongetServerDateCompletedDelegate == null)) {
                this.ongetServerDateCompletedDelegate = new System.Threading.SendOrPostCallback(this.OngetServerDateCompleted);
            }
            base.InvokeAsync(this.onBegingetServerDateDelegate, null, this.onEndgetServerDateDelegate, this.ongetServerDateCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult OutDoor_Guide.WebServiceReference.SyncSoap.BegingetDataBaseDefinitions(OutDoor_Guide.WebServiceReference.getDataBaseDefinitionsRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BegingetDataBaseDefinitions(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult BegingetDataBaseDefinitions(string appName, System.AsyncCallback callback, object asyncState) {
            OutDoor_Guide.WebServiceReference.getDataBaseDefinitionsRequest inValue = new OutDoor_Guide.WebServiceReference.getDataBaseDefinitionsRequest();
            inValue.Body = new OutDoor_Guide.WebServiceReference.getDataBaseDefinitionsRequestBody();
            inValue.Body.appName = appName;
            return ((OutDoor_Guide.WebServiceReference.SyncSoap)(this)).BegingetDataBaseDefinitions(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        OutDoor_Guide.WebServiceReference.getDataBaseDefinitionsResponse OutDoor_Guide.WebServiceReference.SyncSoap.EndgetDataBaseDefinitions(System.IAsyncResult result) {
            return base.Channel.EndgetDataBaseDefinitions(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private string EndgetDataBaseDefinitions(System.IAsyncResult result) {
            OutDoor_Guide.WebServiceReference.getDataBaseDefinitionsResponse retVal = ((OutDoor_Guide.WebServiceReference.SyncSoap)(this)).EndgetDataBaseDefinitions(result);
            return retVal.Body.getDataBaseDefinitionsResult;
        }
        
        private System.IAsyncResult OnBegingetDataBaseDefinitions(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string appName = ((string)(inValues[0]));
            return this.BegingetDataBaseDefinitions(appName, callback, asyncState);
        }
        
        private object[] OnEndgetDataBaseDefinitions(System.IAsyncResult result) {
            string retVal = this.EndgetDataBaseDefinitions(result);
            return new object[] {
                    retVal};
        }
        
        private void OngetDataBaseDefinitionsCompleted(object state) {
            if ((this.getDataBaseDefinitionsCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.getDataBaseDefinitionsCompleted(this, new getDataBaseDefinitionsCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void getDataBaseDefinitionsAsync(string appName) {
            this.getDataBaseDefinitionsAsync(appName, null);
        }
        
        public void getDataBaseDefinitionsAsync(string appName, object userState) {
            if ((this.onBegingetDataBaseDefinitionsDelegate == null)) {
                this.onBegingetDataBaseDefinitionsDelegate = new BeginOperationDelegate(this.OnBegingetDataBaseDefinitions);
            }
            if ((this.onEndgetDataBaseDefinitionsDelegate == null)) {
                this.onEndgetDataBaseDefinitionsDelegate = new EndOperationDelegate(this.OnEndgetDataBaseDefinitions);
            }
            if ((this.ongetDataBaseDefinitionsCompletedDelegate == null)) {
                this.ongetDataBaseDefinitionsCompletedDelegate = new System.Threading.SendOrPostCallback(this.OngetDataBaseDefinitionsCompleted);
            }
            base.InvokeAsync(this.onBegingetDataBaseDefinitionsDelegate, new object[] {
                        appName}, this.onEndgetDataBaseDefinitionsDelegate, this.ongetDataBaseDefinitionsCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult OutDoor_Guide.WebServiceReference.SyncSoap.BeginsetUpdate(OutDoor_Guide.WebServiceReference.setUpdateRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginsetUpdate(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult BeginsetUpdate(string appName, string name, string param, System.AsyncCallback callback, object asyncState) {
            OutDoor_Guide.WebServiceReference.setUpdateRequest inValue = new OutDoor_Guide.WebServiceReference.setUpdateRequest();
            inValue.Body = new OutDoor_Guide.WebServiceReference.setUpdateRequestBody();
            inValue.Body.appName = appName;
            inValue.Body.name = name;
            inValue.Body.param = param;
            return ((OutDoor_Guide.WebServiceReference.SyncSoap)(this)).BeginsetUpdate(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        OutDoor_Guide.WebServiceReference.setUpdateResponse OutDoor_Guide.WebServiceReference.SyncSoap.EndsetUpdate(System.IAsyncResult result) {
            return base.Channel.EndsetUpdate(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private string EndsetUpdate(System.IAsyncResult result) {
            OutDoor_Guide.WebServiceReference.setUpdateResponse retVal = ((OutDoor_Guide.WebServiceReference.SyncSoap)(this)).EndsetUpdate(result);
            return retVal.Body.setUpdateResult;
        }
        
        private System.IAsyncResult OnBeginsetUpdate(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string appName = ((string)(inValues[0]));
            string name = ((string)(inValues[1]));
            string param = ((string)(inValues[2]));
            return this.BeginsetUpdate(appName, name, param, callback, asyncState);
        }
        
        private object[] OnEndsetUpdate(System.IAsyncResult result) {
            string retVal = this.EndsetUpdate(result);
            return new object[] {
                    retVal};
        }
        
        private void OnsetUpdateCompleted(object state) {
            if ((this.setUpdateCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.setUpdateCompleted(this, new setUpdateCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void setUpdateAsync(string appName, string name, string param) {
            this.setUpdateAsync(appName, name, param, null);
        }
        
        public void setUpdateAsync(string appName, string name, string param, object userState) {
            if ((this.onBeginsetUpdateDelegate == null)) {
                this.onBeginsetUpdateDelegate = new BeginOperationDelegate(this.OnBeginsetUpdate);
            }
            if ((this.onEndsetUpdateDelegate == null)) {
                this.onEndsetUpdateDelegate = new EndOperationDelegate(this.OnEndsetUpdate);
            }
            if ((this.onsetUpdateCompletedDelegate == null)) {
                this.onsetUpdateCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnsetUpdateCompleted);
            }
            base.InvokeAsync(this.onBeginsetUpdateDelegate, new object[] {
                        appName,
                        name,
                        param}, this.onEndsetUpdateDelegate, this.onsetUpdateCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult OutDoor_Guide.WebServiceReference.SyncSoap.BegingetTableData(OutDoor_Guide.WebServiceReference.getTableDataRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BegingetTableData(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult BegingetTableData(string appName, string name, string param, System.AsyncCallback callback, object asyncState) {
            OutDoor_Guide.WebServiceReference.getTableDataRequest inValue = new OutDoor_Guide.WebServiceReference.getTableDataRequest();
            inValue.Body = new OutDoor_Guide.WebServiceReference.getTableDataRequestBody();
            inValue.Body.appName = appName;
            inValue.Body.name = name;
            inValue.Body.param = param;
            return ((OutDoor_Guide.WebServiceReference.SyncSoap)(this)).BegingetTableData(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        OutDoor_Guide.WebServiceReference.getTableDataResponse OutDoor_Guide.WebServiceReference.SyncSoap.EndgetTableData(System.IAsyncResult result) {
            return base.Channel.EndgetTableData(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private string EndgetTableData(System.IAsyncResult result) {
            OutDoor_Guide.WebServiceReference.getTableDataResponse retVal = ((OutDoor_Guide.WebServiceReference.SyncSoap)(this)).EndgetTableData(result);
            return retVal.Body.getTableDataResult;
        }
        
        private System.IAsyncResult OnBegingetTableData(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string appName = ((string)(inValues[0]));
            string name = ((string)(inValues[1]));
            string param = ((string)(inValues[2]));
            return this.BegingetTableData(appName, name, param, callback, asyncState);
        }
        
        private object[] OnEndgetTableData(System.IAsyncResult result) {
            string retVal = this.EndgetTableData(result);
            return new object[] {
                    retVal};
        }
        
        private void OngetTableDataCompleted(object state) {
            if ((this.getTableDataCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.getTableDataCompleted(this, new getTableDataCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void getTableDataAsync(string appName, string name, string param) {
            this.getTableDataAsync(appName, name, param, null);
        }
        
        public void getTableDataAsync(string appName, string name, string param, object userState) {
            if ((this.onBegingetTableDataDelegate == null)) {
                this.onBegingetTableDataDelegate = new BeginOperationDelegate(this.OnBegingetTableData);
            }
            if ((this.onEndgetTableDataDelegate == null)) {
                this.onEndgetTableDataDelegate = new EndOperationDelegate(this.OnEndgetTableData);
            }
            if ((this.ongetTableDataCompletedDelegate == null)) {
                this.ongetTableDataCompletedDelegate = new System.Threading.SendOrPostCallback(this.OngetTableDataCompleted);
            }
            base.InvokeAsync(this.onBegingetTableDataDelegate, new object[] {
                        appName,
                        name,
                        param}, this.onEndgetTableDataDelegate, this.ongetTableDataCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override OutDoor_Guide.WebServiceReference.SyncSoap CreateChannel() {
            return new SyncSoapClientChannel(this);
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration) {
            if ((endpointConfiguration == EndpointConfiguration.SyncSoap)) {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.MaxReceivedMessageSize = int.MaxValue;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration) {
            if ((endpointConfiguration == EndpointConfiguration.SyncSoap)) {
                return new System.ServiceModel.EndpointAddress("http://37.187.168.96/TRC_Chauffeur_dev/Sync.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding() {
            return SyncSoapClient.GetBindingForEndpoint(EndpointConfiguration.SyncSoap);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress() {
            return SyncSoapClient.GetEndpointAddress(EndpointConfiguration.SyncSoap);
        }
        
        private class SyncSoapClientChannel : ChannelBase<OutDoor_Guide.WebServiceReference.SyncSoap>, OutDoor_Guide.WebServiceReference.SyncSoap {
            
            public SyncSoapClientChannel(System.ServiceModel.ClientBase<OutDoor_Guide.WebServiceReference.SyncSoap> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult Begincarre(int a, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = a;
                System.IAsyncResult _result = base.BeginInvoke("carre", _args, callback, asyncState);
                return _result;
            }
            
            public int Endcarre(System.IAsyncResult result) {
                object[] _args = new object[0];
                int _result = ((int)(base.EndInvoke("carre", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult Beginhello(OutDoor_Guide.WebServiceReference.helloRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("hello", _args, callback, asyncState);
                return _result;
            }
            
            public OutDoor_Guide.WebServiceReference.helloResponse Endhello(System.IAsyncResult result) {
                object[] _args = new object[0];
                OutDoor_Guide.WebServiceReference.helloResponse _result = ((OutDoor_Guide.WebServiceReference.helloResponse)(base.EndInvoke("hello", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginVerifyWb(OutDoor_Guide.WebServiceReference.VerifyWbRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("VerifyWb", _args, callback, asyncState);
                return _result;
            }
            
            public OutDoor_Guide.WebServiceReference.VerifyWbResponse EndVerifyWb(System.IAsyncResult result) {
                object[] _args = new object[0];
                OutDoor_Guide.WebServiceReference.VerifyWbResponse _result = ((OutDoor_Guide.WebServiceReference.VerifyWbResponse)(base.EndInvoke("VerifyWb", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BegingetServerDate(OutDoor_Guide.WebServiceReference.getServerDateRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("getServerDate", _args, callback, asyncState);
                return _result;
            }
            
            public OutDoor_Guide.WebServiceReference.getServerDateResponse EndgetServerDate(System.IAsyncResult result) {
                object[] _args = new object[0];
                OutDoor_Guide.WebServiceReference.getServerDateResponse _result = ((OutDoor_Guide.WebServiceReference.getServerDateResponse)(base.EndInvoke("getServerDate", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BegingetDataBaseDefinitions(OutDoor_Guide.WebServiceReference.getDataBaseDefinitionsRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("getDataBaseDefinitions", _args, callback, asyncState);
                return _result;
            }
            
            public OutDoor_Guide.WebServiceReference.getDataBaseDefinitionsResponse EndgetDataBaseDefinitions(System.IAsyncResult result) {
                object[] _args = new object[0];
                OutDoor_Guide.WebServiceReference.getDataBaseDefinitionsResponse _result = ((OutDoor_Guide.WebServiceReference.getDataBaseDefinitionsResponse)(base.EndInvoke("getDataBaseDefinitions", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginsetUpdate(OutDoor_Guide.WebServiceReference.setUpdateRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("setUpdate", _args, callback, asyncState);
                return _result;
            }
            
            public OutDoor_Guide.WebServiceReference.setUpdateResponse EndsetUpdate(System.IAsyncResult result) {
                object[] _args = new object[0];
                OutDoor_Guide.WebServiceReference.setUpdateResponse _result = ((OutDoor_Guide.WebServiceReference.setUpdateResponse)(base.EndInvoke("setUpdate", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BegingetTableData(OutDoor_Guide.WebServiceReference.getTableDataRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("getTableData", _args, callback, asyncState);
                return _result;
            }
            
            public OutDoor_Guide.WebServiceReference.getTableDataResponse EndgetTableData(System.IAsyncResult result) {
                object[] _args = new object[0];
                OutDoor_Guide.WebServiceReference.getTableDataResponse _result = ((OutDoor_Guide.WebServiceReference.getTableDataResponse)(base.EndInvoke("getTableData", _args, result)));
                return _result;
            }
        }
        
        public enum EndpointConfiguration {
            
            SyncSoap,
        }
    }
}
